### ISSUE TITLE
Ping Doesnt Work

### ISSUE THREAD

**Issue by MrGiga** [tronyx/Docker-Nagios#2]
**Describe the issue/bug**
Nagios returns "HOST ALERT: **** ;DOWN;HARD;10;CRITICAL - Could not interpret output from ping command"

**To Reproduce**
Standard use.

**Expected behavior**
Nagios should be able to interpret the output from the ping command

**Actual behavior**
A clear and concise description of what is actually happening

**Screenshots/CLI Output**
If applicable, add screenshots or CLI output to help explain your problem.

**Additional context**
Solution is the following command: chmod u+s /bin/ping

**Comment by tronyx** [comment]
That's odd because mine works just fine.
