### ISSUE TITLE
NagiosGraph CGI Installed In Wrong Place

### ISSUE THREAD

**Issue by MrGiga** [tronyx/Docker-Nagios#3]
**Describe the issue/bug**
None of the cgi calls from Nagiosgraph are accessible through HTTP

**To Reproduce**
http://host:8080/nagios/cgi-bin/show.cgi 
http://host:8080/nagios/cgi-bin/showconfig.cgi 

**Expected behavior**
http://host:8080/nagios/cgi-bin/show.cgi should not return 404
http://host:8080/nagios/cgi-bin/showconfig.cgi should not return 404

**Actual behavior**
A clear and concise description of what is actually happening

**Screenshots/CLI Output**

![image](https://user-images.githubusercontent.com/11823603/107420570-080d2180-6ae7-11eb-9f09-81dcdfef0ed7.png)
![image](https://user-images.githubusercontent.com/11823603/107420637-1a875b00-6ae7-11eb-978b-17a65ce30a20.png)

**Additional context**
Looks like the cgi files are installed in /usr/sbin instead of /opt/nagios/sbin

**Comment by CL3M3N5** [comment]
workaround:
cp /usr/sbin/show* /opt/nagios/sbin/
chown nagios:nagios /opt/nagios/sbin/show*

**Comment by JOduMonT** [comment]
> cp /usr/sbin/show* /opt/nagios/sbin/
> chown nagios:nagios /opt/nagios/sbin/show*

even with this nagiosgraph appear with thoses error:
```
JavaScript is disabled.
nagiosgraph.js is not installed or wrong version.
```

**Comment by MrGiga** [comment]
Ok so I ended up making my own image and using that. Here is part of my solution that applies to this:

`RUN echo 'Alias /nagiosgraph "/opt/nagios/share"' >> /etc/apache2/conf.d/nagios.conf<br />
RUN echo 'ScriptAlias /nagiosgraph/cgi-bin "/opt/nagios/sbin"' >> /etc/apache2/conf.d/nagios.conf  
RUN cp ${NAGIOS_GRAPH_HOME}/share/nagiosgraph.* ${NAGIOS_HOME}/share/`

I may be accidentally leaving some stuff out since these are only snippets from my Dockerfile. Let me know if you get errors after this and I'll provide the solution.

My implementation works 100% and has SSL (that was such a pain to implement)

Edit: I'm struggling here trying to get newlines in my code example

**Comment by CL3M3N5** [comment]
Did not work for me.
Can not find 
`/etc/apache2/conf.d/nagios.conf`

I use Debian 10

**Comment by CL3M3N5** [comment]
this worked for me:
echo 'Alias /nagiosgraph "/opt/nagios/share"' >> etc/apache2/sites-available/nagios.conf
echo 'ScriptAlias /nagiosgraph/cgi-bin "/opt/nagios/sbin"' >> etc/apache2/sites-available/nagios.conf
cp ${NAGIOS_GRAPH_HOME}/share/nagiosgraph/* ${NAGIOS_HOME}/share/
chown nagios:nagios ${NAGIOS_HOME}/share/nagiosgraph.*

cp /usr/sbin/show* /opt/nagios/sbin/
chown nagios:nagios /opt/nagios/sbin/show*

**Comment by Pixy123** [comment]
> 
> 
> this worked for me:
> echo 'Alias /nagiosgraph "/opt/nagios/share"' >> etc/apache2/sites-available/nagios.conf
> echo 'ScriptAlias /nagiosgraph/cgi-bin "/opt/nagios/sbin"' >> etc/apache2/sites-available/nagios.conf
> cp ${NAGIOS_GRAPH_HOME}/share/nagiosgraph/* ${NAGIOS_HOME}/share/
> chown nagios:nagios ${NAGIOS_HOME}/share/nagiosgraph.*
> 
> cp /usr/sbin/show* /opt/nagios/sbin/
> chown nagios:nagios /opt/nagios/sbin/show*

it work also for me. Thanks

**Comment by tronyx** [comment]
I will look into getting this fix implemented. Feel free to open a PR as well.

**Comment by tronyx** [comment]
@JOduMonT @MrGiga @Pixy123 @CL3M3N5 - Please test using the develop tag of the image as some fixes from the above PR were merged.

**Comment by tronyx** [comment]
Issue seems resolved, as the provided example URLs no longer throw a 404 error so I am closing this and merging the changes into master.
