### ISSUE TITLE
latest image?

### ISSUE THREAD

**Issue by pahles** [tronyx/Docker-Nagios#38]
Hi, does the 'latest' image still need to be tagged 'latest' or are there more changes coming?

**Comment by tronyx** [comment]
I'm not sure I follow. The `:latest` tag is just for the master branch and is the same as not using a tag. I use the `:develop` tag to test updates before I merge them into the master branch.

**Comment by pahles** [comment]
I just removed every image. If I do a `docker pull tronyx/nagios` it pulls the 'latest' image of 4 months ago.

https://hub.docker.com/r/tronyx/nagios/tags?page=&page_size=&ordering=&name=latest

https://github.com/tronyx/Docker-Nagios/pkgs/container/nagios/198164268?tag=latest

**Comment by tronyx** [comment]
There have been a lot of updates over the last few months. I try to let things bake in the `:develop` tag for a few weeks before I merge them into master/latest, but I've been very busy with life. I actually JUST merged today, but it looks like there is something missing from the build script that is no longer tagging `:latest` for some reason. You can use the `:master` tag if you'd like until I get this fixed.

**Comment by tronyx** [comment]
I believe I found the issue and am running builds now.

**Comment by tronyx** [comment]
Fix is confirmed: https://hub.docker.com/repository/docker/tronyx/nagios/tags?page=&page_size=&ordering=&name=latest
