### ISSUE TITLE
Container log full of 'nsca configuration not found; skipping.'

### ISSUE THREAD

**Issue by ricjuhnl** [tronyx/Docker-Nagios#42]
**Describe the issue/bug**
After we build Nagios and container started, the logs are being spam filled with the message 'nsca configuration not found; skipping.

**To Reproduce**
- Build FROM tronyx/nagios:ubuntu-22.04 without nsca config

**Expected behavior**
nsca addon not loaded when config is missing. 

**Actual behavior**
Nagios is running as expected, but the logs are filled with this message which makes it hard to find actual error logs.

**Screenshots/CLI Output**
![nagios_logs](https://github.com/user-attachments/assets/106cf0dc-20f4-4bea-8837-eca6c18a27ee)

**Comment by tronyx** [comment]
I do not believe that this is an issue with the image. I cannot reproduce this by running the image on a fresh VM with no changes. The image includes an NSCA config file by default so what is your process doing that is removing it?

`:~# docker run --rm -p 88:80 tronyx/nagios:ubuntu-22.04 ls -la /opt/nagios/etc/nsca.cfg`
`-rw------- 1 nagios nagios 5645 Dec 14 13:42 /opt/nagios/etc/nsca.cfg`

**Comment by ricjuhnl** [comment]
I will `cat` the default cfg file and add it to our external /nagios/etc folder. That will be the fastest and easiest solution i guess.

Don't know what caused this issue because we never had an nsca.cfg file in our nagios build.

**Comment by tronyx** [comment]
Shouldn't be a need to `cat` the file or do anything else. If you mount the config directory as shown in the README, `/path-to-nagios/etc/:/opt/nagios/etc/`, the `nsca.cfg` file should just be there as you can see here:

```
:~# mkdir -p /home/nagios/etc
:~# docker run -d -v /home/nagios/etc/:/opt/nagios/etc/ -p 88:80 tronyx/nagios:ubuntu-22.04
a8aee901d0a821fe3c8c3255686b71c32acbb6feb8faa3c3ca1dbc267cc0e849
:~# ls -la /home/nagios/etc/
total 96
drwxr-xr-x 5  997 tronyx  4096 Dec 17 10:35 .
drwxr-xr-x 3 root root    4096 Dec 17 10:35 ..
-rw-r--r-- 1  997 tronyx 11655 Dec 14 08:40 cgi.cfg
drwxr-xr-x 2  997 tronyx  4096 Dec 14 08:43 conf.d
-rw-r--r-- 1  997 tronyx    46 Dec 17 10:35 htpasswd.users
drwxr-xr-x 2  997 tronyx  4096 Dec 14 08:43 monitor
-rw-r--r-- 1  997 tronyx 44602 Dec 14 08:43 nagios.cfg
-rw------- 1  997 tronyx  5645 Dec 14 08:42 nsca.cfg   <--------------------
drwxr-xr-x 2  997 tronyx  4096 Dec 14 08:40 objects
-rw-rw---- 1  997 tronyx  1300 Dec 14 08:41 resource.cfg
-rw------- 1  997 tronyx  1834 Dec 14 08:42 send_nsca.cfg
```

**Comment by ricjuhnl** [comment]
Yeah the problem is that we mount our volume in 'readonly', so that why the cfg is not written. 
I will close this issue. Thanks for the quick replies!
