### ISSUE TITLE
missing plugins

### ISSUE THREAD

**Issue by Pixy123** [tronyx/Docker-Nagios#5]
Hi, in your docker container missing this plugin
http://nagios-plugins.org/doc/man/check_by_ssh.html
You have idea how to resolve?
Original "jasonrivers/nagios" it have and work.
Thanks

**Comment by Pixy123** [comment]
I have find issue... You do install "openssh-client" and compile nagios-plugin

**Comment by tronyx** [comment]
So what is the issue?

**Comment by Pixy123** [comment]
You do install "openssh-client" and compile nagios-plugin

**Comment by tronyx** [comment]
Ok, so is there an issue still or not? I am confused.

**Comment by Pixy123** [comment]
yes, you do add package in dockerfile..this line
>>  apt-get -qq -y install --no-install-recommends openssh-client

**Comment by tronyx** [comment]
Ok, I am still unable to understand the issue here. I believe it may be a language barrier.

It doesn't seem that I am installing that package. Should that package be installed? What is missing? What EXACTLY is the real issue here?

**Comment by Pixy123** [comment]
Like write over... 
> I have find issue... You do install "openssh-client" and compile nagios-plugin

You do add that package before compile nagios

You can add in dockerfile at line 35 during apt get install command

**Comment by tronyx** [comment]
Added it with https://github.com/tronyx/Docker-Nagios/commit/d588842097e75c21a9bc30a60641df6a2e204625 so please try the `:develop` tag of the image and let me know.

**Comment by Pixy123** [comment]
Hi it's correct. I have compiled many time ago like that

**Comment by tronyx** [comment]
Ok, then I am good to close the issue?

**Comment by Pixy123** [comment]
Yes thank you
